Bookstore: styling
Nessrine88/Bookstore pull request #5
Opened 2023-09-01 18:09 UTC by Nessrine88

### Project requirements

- Add any missing JSX elements to the project 
- The final design match Zeplin's design 
-  Using the CSS rules detailed in Zeplin to style the website.

2023-09-01 20:11 UTC, Munsa1 requested changes
Hi @Nessrine88, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
Followed Given Design :heavy_check_mark: 
Good UI Design :heavy_check_mark: 
No Inline Styles :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-01 20:11 UTC, Munsa1 commented on src/style/Book.css
> +}
- [ ] Please use reusable classes for reoccurring CSS styles. For example consider grouping the following styles then using that class on all the desired components:



```
### Example
.reusable-class{

  font-family: 'RobotoSlab', sans-serif;
  font-stretch: normal;
  font-style: normal;
  line-height: normal;
}
```

### Note that this should be applied to `navigation.css` file as well

2023-09-01 20:11 UTC, Munsa1 commented on src/style/Navigation.css
> +  display: flex;
- [ ] The same here, `display: flex` is used three times in this file, using a reusable class helps make our code DRY

2023-09-01 20:11 UTC, Munsa1 commented on src/style/Book.css
> +  color: var(--black-two);
- [ ] The same thing here consider using a reusable class for this `color: var(--black-two);` as you have used it 4 times in this file

2023-09-01 20:11 UTC, Munsa1 commented on src/style/BookForm.css
>    border: 1px solid #ccc;
- [ ] The same thing applies to this border style, it is being used accross multiple CSS files, the DRY principle means that we apply it in one file as a reusable class then simply import that CSS file into all the affected components, than having it repeat in each CSS file

2023-09-01 20:11 UTC, Munsa1 commented on src/components/Navigation.js
> +            </li>
- [ ] Kindly follow the given design in terms of styling for the following part of the app\

Your design
![image](https://github.com/Nessrine88/Bookstore/assets/81932478/25c7a5ec-3040-4eac-b0b2-49436be339a7)

Given design
![image](https://github.com/Nessrine88/Bookstore/assets/81932478/f102bb26-374f-438f-941a-11fb1ec6bcfb)

2023-09-01 20:11 UTC, Munsa1 commented on src/components/Book.js
> +        <button type="button" className="btn">UPDATE PROGRESS</button>
- [x] In the given design this text uses the `RobotoSlab-Light` font while yours is using the Arial font, kindly fix this


Note that this applies for the `Add Book` button as well
![image](https://github.com/Nessrine88/Bookstore/assets/81932478/991781c0-dbca-43a2-bfac-ac7cddabfe64)

2023-09-01 20:11 UTC, Munsa1 commented on src/components/Book.js
> +        <p className="chapter">Chapter 17</p>
- [ ] Kindly use the correct font for the `Chapter` text as well so as to match the given design

Your design
![image](https://github.com/Nessrine88/Bookstore/assets/81932478/7a317def-c401-4895-950c-566b8a3b702c)

Given design
![image](https://github.com/Nessrine88/Bookstore/assets/81932478/e25dc09d-c38c-43c3-8caa-a0dd58452ee5)

2023-09-01 20:11 UTC, Munsa1 commented on src/components/BookForm.js
> +        </select>
- [ ] Kindly consider adding the correct font to the input placholder text and to the drop down selection inorder to match the given design

Your design
![image](https://github.com/Nessrine88/Bookstore/assets/81932478/6bef1b97-e59c-49c9-9fe9-a6c4e0bdc2ee)

Given design
![image](https://github.com/Nessrine88/Bookstore/assets/81932478/14eae41b-5995-485c-8444-44c0357d5554)

Note that your dropdown menu is grey in color while the given one is white

2023-09-02 07:51 UTC, KDlamini approved these changes
### Hi @Nessrine88 🙋‍♀️,  

Excellent work! 💯 
You have done a great job implementing all the required changes. 🎊 🥳 
Your feature is complete! There is nothing else to say other than... it's time to merge it. :shipit: 
Congratulations!!!

## HIGHLIGHTS 🌟 

✔️ Professional PR title and description
✔️ Styling matches the given Zeplin design
✔️ The app makes use of basic CSS best practices

# Status: Approved ✔️ 

![LeonardoInGatsby](https://github.com/Nessrine88/Bookstore/assets/38088818/f057f338-6749-404b-9d36-523d85c9ef3b)

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-03 18:45 UTC, merged